apiVersion: apps/v1
kind: Deployment
metadata:
  name: errorproxy
  labels:
    app: errorproxy
spec:
  selector:
    matchLabels:
      app: errorproxy
      tier: web
  template:
    metadata:
      labels:
        app: errorproxy
        tier: web
    spec:
      containers:
      - name: errorproxy
        image: umiyosh/errorproxy:latest
        env:
        - name: SERVER_NAME
          value: 'localhost'
        - name: WORKER_PROCESSES
          value: '1'
        - name: WORKER_CONNECTIONS
          value: '1024'
        - name: UPSTREAM_NAME
          value: 'hello-app:8080'
        - name: UPSTREAM_KEEPALIVE
          value: '2000'
        - name: ERROR_RATE
          value: '10'
        ports:
        - containerPort: 8080
