apiVersion: apps/v1
kind: Deployment
metadata:
  name: errorproxy
  labels:
    app: errorproxy
spec:
  selector:
    matchLabels:
      app: errorproxy
      tier: web
  template:
    metadata:
      labels:
        app: errorproxy
        tier: web
    spec:
      containers:
      - name: errorproxy
        image: umiyosh/errorproxy:latest
        env:
        - name: SERVER_NAME
          value: '127.0.0.1'
        - name: WORKER_PROCESSES
          value: '1'
        - name: WORKER_CONNECTIONS
          value: '1024'
        # - name: UPSTREAM_NAME
          # value: 'hello-app:8080'
        - name: UPSTREAM_NAME
          value: '127.0.0.1:8082'
        - name: UPSTREAM_KEEPALIVE
          value: '2000'
        - name: ERROR_RATE
          value: '80'
        - name: LATENCY_ERR_MS
          value: '5000'
        - name: LATENCY_OK_MS
          value: '0'
        - name: LISTEN_PORT
          value: '8080'
        ports:
        - containerPort: 8080
