apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: errorproxy
        image: umiyosh/errorproxy:latest
        env:
        - name: SERVER_NAME
          value: '127.0.0.1'
        - name: WORKER_PROCESSES
          value: '1'
        - name: WORKER_CONNECTIONS
          value: '1024'
        - name: UPSTREAM_NAME
          value: '127.0.0.1:8080'
        - name: UPSTREAM_KEEPALIVE
          value: '2000'
        - name: ERROR_RATE
          value: '10'
        - name: LISTEN_PORT
          value: '8000'
        ports:
        - containerPort: 8000
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
